module.exports = {
  welcome: 'Welcome!',
  intro_paragraph: 'Welcome to the Noise Complaint App! This app serves two purposes: to help inform about Copenhagen’s noise complaint process and to collect nightlife noise complaint data. The app will walk you through the process of submitting a noise complaint. Currently, we are only accepting noise complaints pertaining to street noise and private celebrations; however, the app will walk you through the process of submitting any other type of noise complaint to the proper authorities.',
  testing_paragraph1: 'For the testing period, we ask you to create a username and password that will allow you into the noise complaint system. Please visit the create an account tab at the top of the screen to do so.',
  testing_paragraph2: 'Please note that this app is not finished yet and is currently being worked on. Before our system becomes available to the public we will be clearing the database of all complaints, and accounts created during the testing period. However, please refrain from submitting any personal information in a complaint as we are still actively improving the data security systems.',
  disclaimer: 'Disclaimer',
  disclaimer_paragraph: 'Your noise complaint submission will be sent to our database for noise disturbance data collection. For any emergencies, please contact the police at 114.',
  // Version 1.0 Changes
  intro_paragraph2: 'Welcome to the Stop Støj App! This app serves two purposes: to help inform people about Copenhagen’s noise complaint process and to collect nightlife noise complaint data. These data will be used to build a model of the nightlife noise issues in inner city Copenhagen. This model can provide valuable nightlife insight to the police and city officials, potentially improving nightlife management processes and living conditions.',
  secondary_paragraph: 'The app will walk you through the process of submitting a noise report. This report will be filed with Miljøpunkt Indre By & Christianshavn for data analysis and advocacy purposes. Upon submission, the app will direct you towards the proper authority and automatically give you contact information so you can request immediate action on the incident.',
  security_paragraph: 'Please note that this app is not completed yet. Please refrain from submitting any personal information in a report as we cannot currently guarantee that the data will remain completely secured.'
}
