module.exports = {
  submit_a_complaint: 'Submit A Complaint',
  logged_in_warn: 'You must be logged in to submit a complaint',
  logged_in_warn2: 'You must be logged in',
  log_in_here: 'You can log in here',
  logged_in_as: 'You are currently logged in as: ',
  press_next: 'Press next to continue',
  category: 'Category',
  select_category: 'Select Category',
  sub_category: 'Sub Category',
  select_noise: 'Select Noise Type',
  location_address: 'Location (Search by Address):',
  search: 'Search',
  reset: 'Reset',
  drag_pin: 'Please drag the arrow to your location.',
  comments: 'Comments:',
  thank_you: 'Thank You',
  complaint_submitted: 'Your complaint has been submitted',
  immediate_action: 'If you require immediate action, please call the police at 114.',
  redirect_heading: 'Please contact another authority!',
  only_accepting_for: 'We are currently only accepting complaints from the following categories:',
  kkdkredirect: 'If you would like to submit a complaint about anything else, please visit the København Kommune’s noise complaint form via this link:',
  noise_authority_redirect: 'If you would like to submit a complaint about noise generated by cafes, restaurants, events or other venues, please contact the Noise Unit during the day or the Noise Guard at night.',
  noise_unit_hours: 'Noise Unit: Man-Tors 9:00-15:00. Tel. 26 86 58 27',
  noise_guard_hours: 'Noise Guard: Tors 19:00-01:00, Fre-Lør 21:00-03:00. Tel. 33 66 25 85',
  next: 'Next',
  back: 'Back',
  submit: 'Submit',
  invalid_complaint: 'Invalid Complaint',
  invalid_complaint_desc: 'Please insure that your complaint has a category, subcategory, and location selected before submitting',
  street_noise: 'Street Noise',
  loud_music_party: 'Loud Music/Party',
  loud_talking_shouting: 'Loud Talking/Shouting',
  private_celebration: 'Private Celebration',
  banging_pounding: 'Banging/Pounding',
  bar_restaurant: 'Bar/Restaurant',
  construction: 'Construction',
  your_complaint_categorized: 'Your report has been collected and was categorized as ', // Gtranslated
  file_formal_police: 'To file a formal complaint, please call the police at 114.', // Gtranslated
  police_can_help_with: 'The Police can help with noise related to:', // Gtranslated
  file_formal_noise_unit: 'To file a formal complaint, please call the Noise Unit or Noise Guard', // Gtranslated
  file_formal_noise_form: 'Alternatively, you can file a complaint via the Municipality’s noise complaint form', // Gtranslated
  municipality_can_help_with: 'The Municipality can help with noise related to:' // Gtranslated
}
